### ISSUE TITLE
Company behind Trino should be changed to Starburst

### ISSUE THREAD

**Issue by lhoss** [lfai/lfai-landscape#339]
https://github.com/lfai/lfai-landscape/blob/11d5e6b4d41021fb9eaa80826084b7a56886a74b/landscape.yml#L976

Correct Org is **Starburst**: https://www.crunchbase.com/organization/starburst
> Starburst Enterprise, based on open source Trino (formerly PrestoSQL) ..

https://www.crunchbase.com/organization/presto-foundation
should be linked with a different/new product `prestodb`  (if not done already?)

**Comment by ibrahimhaddad** [comment]
Thank you. will be reflected in the landscape in the next update.
