### ISSUE TITLE
Broken link in the install page

### ISSUE THREAD

**Issue by davidradl** [lfai/lfai-landscape#525]
[https://github.com/lfai/lfai-landscape/blob/main/INSTALL.md](https://github.com/lfai/lfai-landscape/blob/main/INSTALL.md ) has a broken link. Line 
"
Please follow [this script](https://github.com/cncf/landscapeapp/blob/master/update_server/setup.template) to install correct versions of nodejs and other packages on Linux."

Page [https://github.com/cncf/landscapeapp/blob/master/update_server/setup.template](https://github.com/cncf/landscapeapp/blob/master/update_server/setup.template )does not exist.

I followed the instructions to run locally the npm command returned with no out put or error seemingly doing nothing. I assume I have the wrong levels of node and npm, which would be detailed in this script.

**Comment by davidradl** [comment]
it looks like folder blob is not checked into Git - it might be a generated file.

**Comment by davidradl** [comment]
I notice the install instructions refer to lfdl-landscape.git - shouldn't they refer to this git repo?

**Comment by ibrahimhaddad** [comment]
We rebranded from LFDL (LF Deep Learning) to LF AI & Data and some links or references need to be updated. Thanks for flagging.

**Comment by ibrahimhaddad** [comment]
Fixed. thx.
