### ISSUE TITLE
Egeria not appearing as an Apache 2.0 project - but yml looks ok

### ISSUE THREAD

**Issue by mandy-chessell** [lfai/lfai-landscape#547]
I noticed that the Egeria project was not appearing as an Apache 2.0 licensed project.  I went to correct the yml file but it looks ok.  What am I missing?

Extract from the yml file
```
            name: Egeria
            license: Apache 2.0
            homepage_url: https://egeria-project.org
            project: graduated
            repo_url: https://github.com/odpi/egeria
```
Many thanks

**Comment by mandy-chessell** [comment]
I have been doing some more investigating and the problem is that there are two menu items for the Apache 2.0 license:
<img width="340" alt="Screenshot 2023-03-10 at 11 00 26" src="https://user-images.githubusercontent.com/12354195/224299670-137c919d-9ea0-4d4a-8d46-82f3a1f0cf4d.png">

If both options are clicked then Egeria appears.

Is it possible to consolidate all of the Apache 2.0 projects into one collection?

**Comment by ibrahimhaddad** [comment]
resolved.
